---
fixtures:
  repositories:
    stdlib:  https://github.com/puppetlabs/puppetlabs-stdlib.git
    simplib: https://github.com/simp/pupmod-simp-simplib
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
  symlinks:
    incron: "#{source_dir}"
