---
fixtures:
  repositories:
    stdlib:   "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    simplib:   "https://github.com/simp/pupmod-simp-simplib.git"
    simpcat:   "https://github.com/simp/pupmod-simp-simpcat.git"
  symlinks:
    incron: "#{source_dir}"
